- Dockerfile.static
building on #10 but now the args are passed through to the entrypoint.
I'm still not seeing that `-f` keeps it in the foreground though.
> Dockerfile: foreground and allow args to fuse-overlayfs

- main.c
While fuse-overlayfs doesn't set this xattr, ensure that we honor it when it exists so that we report the correct st_ino on lower layers that were created using the kernel implementation.
> fuse-overlayfs: honor trusted.overlay.origin

- rpm/fuse-overlayfs.spec.template
On a freshly installed system (F28) installing `fuse-overlayfs` package is insufficient to run it:
```
fuse-overlayfs -o lowerdir=lowerdir -o upperdir=upperdir -o workdir=workdir mountdir
UID=unchanged
GID=unchanged
UPPERDIR=/home/core/fuse/upperdir
WORKDIR=workdir
LOWERDIR=lowerdir
MOUNTPOINT=mountdir
fuse: failed to exec fusermount3: No such file or directory
```
```
dnf provides fusermount3
Last metadata expiration check: 0:53:07 ago on Mon 15 Oct 2018 06:15:49 PM UTC.
fuse3-3.2.1-11.fc28.x86_64 : File System in Userspace (FUSE) v3 utilitie
Repo        : fedora
Matched from:
Filename    : /usr/bin/fusermount3
```
This small change adds `fuse3` as a `fuse-overlayfs`  dependency.
> adding missing dependency

- .travis.yml
- main.c
if mknod fails with ENOTSUP then use the .wh.FILE variant.
Closes: https://github.com/containers/fuse-overlayfs/issues/17
> fuse-overlayfs: try alternative whiteout on ENOTSUP

- main.c
do not follow symlinks when stat'ing a path, so that we read the inode
of the symlink itself.
Closes: https://github.com/containers/fuse-overlayfs/issues/23
> fuse-overlayfs: read correctly inode for dangling symlinks

- .travis.yml
- main.c
before we were not testing the .wh. variant in Travis.
Enable tests and fix a couple of issues reported by the overlay testsuite
> fuse-overlayfs: fix a couple of issues with the .wh. variant and enable tests

- main.c
be sure we are able to set all the bits on created files/directories.
> fuse-overlayfs: set umask to 0

- main.c
propagate the error code to the caller if the lower file cannot be
opened.
> copyup: fix error if lower file cannot be opened

- main.c
Addresses: https://github.com/containers/buildah/issues/1240#issuecomment-448949403
> fuse-overlayfs: set suid when running in a user namespace

- main.c
Closes: https://github.com/containers/fuse-overlayfs/issues/35
> fuse-overlayfs: use allow_other only when running with uid=0

- main.c
> main: ignore EINVAL when copying xattrs

- main.c
fix an interesting interaction between unlink(2) and readdir(2) that
can confuse the cache.
If a file is unlinked before the readdir(2) is done, it is not removed
from the list generated when the directory was first opened.  Thus the
result is that readdir(2) will return the file even if it was unlinked
and moved to the work dir until the cache is released.
The fix is to skip dentries that are hidden while iterating the list.
Closes: https://github.com/containers/libpod/issues/2342
> fuse-overlays: fix interaction of unlink(2) with readdir(2)

- .travis.yml
- Makefile.am
- main.c
- tests/fedora-installs.sh
- utils.h
first pass at using `__attribute__((cleanup))`.  It helps to simplify a lot of code, and hopefully avoid some bugs.
We should ideally add custom cleanup functions for the structs we are defining.
> fuse-overlayfs: use autocleanup functions

- main.c
it solves this error on copy_xattrs when the underlying file system is
overlay:
flistxattr(9, "security.selinux\0", 1048576) = 17
fgetxattr(9, "security.selinux", "system_u:object_r:container_file"..., 256) = 48
fsetxattr(10, "security.selinux", "system_u:object_r:container_file"..., 48, 0) = -1
> fuse-overlayfs: ignore xattrs copy errors when not supported

- README.md
we require FUSE 3.2.1, update the README to reflect it.
Closes: https://github.com/containers/fuse-overlayfs/issues/48
> README.md: update fuse version

- main.c
when looking up multiple layers and we have already found a file, do
not check if whiteouts are present in lower layers.  The lookup in the
lower layers is needed only to correctly propagate the inode number.
> fuse-overlayfs: fix lookup with multiple layers

- .travis.yml
- main.c
- tests/unlink.sh
fix a regression introduced by f64f65287817fecd0 that prevents a
whiteout file to be created on the first unlink.
> fuse-overlayfs: fix first unlink done

- configure.ac
- main.c
attempt to use sendfile(2) before falling back to a read/write loop.
> copyup: use sendfile(2) if available

- main.c
avoid to send an error response twice.
> ioctl: return immediately with not implemented ioctls

- main.c
don't block on writing to the pipe.  It has a significant impact on
the performance.
> fuse-overlayfs: write uses SPLICE_MOVE|SPLICE_NONBLOCK

- main.c
- tests/fedora-installs.sh
Closes: https://github.com/containers/fuse-overlayfs/issues/69
> fuse-overlayfs: do not copyup a whiteout on rename

- Dockerfile.static
- README.md
There were three problems with the static build instructions:
1. `buildah` can't find an image without a search repository configured
1. I was getting a build error about missing compilers until I added clang
1. The readme had the `-t` and `-f` flags mixed up
With these changes, I was able to build with buildah `1.9.0-dev` :tada:
> Update static build instructions

- main.c
if we are looking for a path in a lower component, skip ENOTDIR as a
component might be a whiteout.
This happens only when running as root, as the whiteout takes the same
name of the deleted file/directory.
> main: skip ENOTDIR in a lookup

- main.c
fix this warning:
main.c:3870:13: warning: initialization of ‘void (*)(struct fuse_req
*, fuse_ino_t,  unsigned int,  void *, struct fuse_file_info *,
unsigned int,  const void *, size_t,  size_t)’ {aka ‘void (*)(struct
fuse_req *, long unsigned int,  unsigned int,  void *, struct
fuse_file_info *, unsigned int,  const void *, long unsigned int,
long unsigned int)’} from incompatible pointer type ‘void (*)(struct
fuse_req *, fuse_ino_t,  long unsigned int,  void *, struct
fuse_file_info *, unsigned int,  const void *, size_t,  size_t)’ {aka
‘void (*)(struct fuse_req *, long unsigned int,  long unsigned int,
void *, struct fuse_file_info *, unsigned int,  const void *, long
unsigned int,  long unsigned int)’} [-Wincompatible-pointer-types]
3870 |    .ioctl = ovl_ioctl,
| …
> main: fix compiler warning

- main.c
the implementation of flock(2) was wrong and it caused a deadlock when
multiple processes tried to lock the same file.
Drop it and let FUSE handle locking for us.
Closes: https://github.com/containers/fuse-overlayfs/issues/80
> main: drop code to handle flock

- main.c
- utils.h
there are some other performance fixes.
In particular, this PR addresses some issues reported with: https://github.com/containers/fuse-overlayfs/pull/88#issuecomment-513882925
Now operations like readdir/rmdir/unlink require significantly less syscalls.
> fuse-overlayfs: different performance tweaks continuation of #88 

- main.c
an issue introduced by last changes
> fuse-overlayfs: fix a fd leak when creating new files

- lib/hash.c
- main.c
make sure the work directory is empty when fuse-overlayfs starts.
Closes: https://github.com/containers/fuse-overlayfs/issues/93
> main: make sure the work directory is empty

- main.c
the return type is ssize_t, not size_t.
> main: fix type for flistxattr return

- rpm/fuse-overlayfs.spec.template
this is useful to build a development rpm that can be quickly moved
around.
> rpm: sync with Fedora repo

- configure.ac
- main.c
always use the /proc/self/fd/FD path when a fd is not available.
commit 0b0c7a3a01dae4de65ba79016a111d794c1d1719 introduced the regression.
Closes: https://github.com/containers/fuse-overlayfs/issues/99
> main: simplify setattr

- .travis.yml
- main.c
- tests/fedora-installs.sh
when reading xattr, if the path cannot be open as it is a directory, operate on the /proc/fd/FD path.
Closes: https://github.com/containers/fuse-overlayfs/issues/104
> main: if the path is a dir, work on the proc path

- Makefile.am
- NEWS
- configure.ac
- main.c
- tests/unlink.sh
introduce a hash map to refer from an inode to the file paths.
A recent change where we enable FUSE writeback by default uncovered an
underlying issue in fuse-overlayfs where changes to a file with
multiple links would not be visible from the other link.
For each inode, maintain a list of nodes that refer to it, so that we
can still access it when a link is removed and more importantly we can
use the inode value with FUSE.
Closes: https://github.com/containers/fuse-overlayfs/issues/108
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1744109
> main: introduce inodes cache

- main.c
include the st_dev in the inodes map key.  Now if the same ino is used on two different layers backed by a different file system, they are treated as different inodes.
Closes: https://github.com/containers/fuse-overlayfs/issues/112
> [WIP] use st_dev for the inode key

- main.c
disable writeback if it is not supported by FUSE.
Closes: https://github.com/containers/fuse-overlayfs/issues/116
> main: check whether writeback is supported

- main.c
- Setting and getting nofile not process limits
Authored-by: Tyler Ramer <tramer@pivotal.io>
> Fix typo in set_limits

- main.c
It's perfectly possible to set attributes by being the file's owner; one
does not need write access to the contents.
Alternative for: https://github.com/containers/fuse-overlayfs/pull/114
> set_attrs: don't require write to S_IFREG

- NEWS
- configure.ac
- main.c
fix the lookup function to report also a whiteout node, instead of NULL.  This is required to correctly delete the whiteout file when it exists.
Closes: https://github.com/containers/fuse-overlayfs/issues/122
> main: fix skip whiteout deletion optimization

- main.c
after a successful chmod, store the new mode for the ino.
Closes: https://github.com/containers/fuse-overlayfs/issues/124
> main: store the new mode after chmod

- main.c
if the file is present only on the upper layer, do not create a
whiteout when it is created.  Previously it was looking only at the
parent directory.
> main: skip whiteout creation if not needed

- NEWS
- configure.ac
- main.c
- tests/fedora-installs.sh
make sure the directory is reloaded so the correct number of links can
be retrieved.
Closes: https://github.com/containers/fuse-overlayfs/issues/131
> main.c: reload the directory on stat

- README.md
- main.c
- tests/fedora-installs.sh
when there is no upper layer specified, fail every read operation with
EROFS.
Closes: https://github.com/containers/fuse-overlayfs/issues/100
> fuse-overlayfs: support running without upper layer

- Makefile.am
- configure.ac
- direct.c
- fuse-overlayfs.h
- main.c
- plugin-manager.c
- plugin-manager.h
- plugin.h
- tests/fedora-installs.sh
- utils.c
- utils.h
Alternative for https://github.com/containers/fuse-overlayfs/pull/79
Add a simple plugin mechanism that will help to expand fuse-overlayfs
functionalities, in particular it allows to load data from a layer on
demand.
A plugin is loaded into fuse-overlayfs using the option:
-o plugins=path/to/plugin.so:path/to/another/plugin.so
A layer can use a plugin with the syntax:
-o lowerdir=//plugin-name/DATA-FOR-THE-PLUGIN/path
Each time a file/directory is looked up, if a plugin is registered for
a layer, the plugin is first notified about the request.
After the callback is invoked, fuse-overlayfs still expects the data
to be accessible at the specified directory.
Signed-off-by: Giuseppe Scrivano gscrivan@redhat.com
> fuse-overlayfs: add C plugins system

- tests/fedora-installs.sh
verify that setting attributes on a dangling symlink work, even if the
file type is different on a lower layer.
Closes: https://github.com/containers/fuse-overlayfs/issues/143
> tests: test that touch -h works

- configure.ac
- main.c
check if the version of FUSE supports copy_file_range.
It fixes the build on RHEL 8.
> configure: check for FUSE copy_file_range

- plugin-manager.h
Currently the build fails on muslc due to a missing definition (`TEMP_FAILURE_RETRY`) that's only available on glibc.
I've applied [this workaround](https://github.com/ostreedev/ostree/issues/731) and now the build succeeds .
```c
/* taken from glibc unistd.h and fixes musl */
#ifndef TEMP_FAILURE_RETRY
#define TEMP_FAILURE_RETRY(expression) \
(__extension__                                                              \
({ long int __result;                                                     \
do __result = (long int) (expression);                                 \
while (__result == -1L && errno == EINTR);                             \
__result; }))
#endif
```
> muslc: Fix build

- main.c
- tests/fedora-installs.sh
use the full relative path when looking up the whiteout file,
otherwise a whiteout in the upper layer will hide files in
subdirectories.
Closes: https://github.com/containers/fuse-overlayfs/issues/151
> main: prevent parent whiteout to hide file

- Makefile.am
make sure the header files are included in the tarball generated by
"make dist".
> Makefile.am: include header files

- fuse-overlayfs.h
To avoid that the compiler complains when building with `-fno-common`.
Can be reproduced by:
```
> make CFLAGS=-fno-common
...
ld: fuse_overlayfs-direct.o:(.data+0x0): multiple definition of \
`direct_access_ds'; fuse_overlayfs-main.o:(.bss+0x0): \
first defined here
ld: fuse_overlayfs-utils.o:(.bss+0x0): multiple definition of \
`direct_access_ds'; fuse_overlayfs-main.o:(.bss+0x0): \
first defined here
ld: fuse_overlayfs-plugin-manager.o:(.bss+0x0): multiple definition of \
`direct_access_ds'; fuse_overlayfs-main.o:(.bss+0x0): \
first defined here
```
> Fix build with -fno-common

- main.c
If the call to `get_upper_layer(lo)` returns `NULL` then the
`node->layer` will be `NULL`, too. If this is the case we pass `NULL` to
`direct_fsync()` which will cause a segmentation fault in:
```c
cfd = openat(l->fd, path, O_NOFOLLOW|O_DIRECTORY);
```
To fix this we now apply an additional check and error in the case of
`get_upper_layer(lo) == NULL`.
> Fix possible segmentation fault in direct_fsync()

- main.c
if the directory was moved, invalidate its cache and force a reload.
Closes: https://github.com/containers/fuse-overlayfs/issues/160
> main: force a dir reload after a move

- main.c
having the fd open with O_DIRECT causes pwrite64 to fail with EINVAL if the write buffer is not aligned.  Since we have no control on the buffer provided by libfuse, just drop O_DIRECT.
Closes: https://github.com/containers/fuse-overlayfs/issues/167
> main: reset O_DIRECT on open

- main.c
when doing a lookup, make sure the returned file is not a whiteout for
functions that expect the file to exist.
Close: https://github.com/containers/fuse-overlayfs/issues/169
> main: check if file is whiteout

- main.c
The help message that is printed does not match reality for the command line.
Signed-off-by: Daniel J Walsh <dwalsh@redhat.com>
> Add support for debug to match help

- .travis.yml
- NEWS
- configure.ac
- main.c
before doing a rename(2) make sure the destination is cleaned up,
otherwise a left-over directory can cause the rename to fail with
EEXIST.
Closes: https://github.com/containers/fuse-overlayfs/issues/189
> main, rename: make sure destination is deleted

- main.c
stop the lookup for the dev/ino if there is not an ino open as it also
prevents reading the origin xattr.
> main: stop ino lookup without an open fd

- .travis.yml
- direct.c
- plugin-manager.c
- utils.c
it caused an issue on armv7h where different versions of dirent struct
were used in main.c and in the other files.
Regression introduced with c2c2ac5b82fb59322da227d196214b4a58ede634
Closes: https://github.com/containers/fuse-overlayfs/issues/197
> fuse-overlayfs: add missing definitions for _FILE_OFFSET_BITS

- configure.ac
This fixes linker errors for `rpl_malloc` when cross-compiling using Nix.
> Fix cross compilation

- main.c
the copyup function returns the error code set in ret.  Make sure ret
has the correct return code if set_fd_origin fails.
Closes: https://github.com/containers/fuse-overlayfs/issues/211
> main: correctly report copyup error

- NEWS
- configure.ac
- main.c
if the destination already exists as it could not be properly cleaned
up, attempt to atomically swap the two directories and free the old
one.
Closes: https://github.com/containers/fuse-overlayfs/issues/213
> mkdir: if the destination exists atomically swap them

- .github/workflows/release.yaml
- Dockerfile.cross
Fix #187 
Based on https://github.com/rootless-containers/slirp4netns/blob/99e1516d2b8c9187740082a0f975a87cd6a981b4/.github/workflows/release.yaml
Usage:
* Push `vX.Y.Z` tag to origin
* GitHub Action `release` automatically creates a draft release with binaries for x86_64, aarch64, armv7l, s390x, and ppc64le.
* Edit the draft and click the "Public release" button.
---
Logs: https://github.com/AkihiroSuda/fuse-overlayfs/runs/786829271 (Took 2m4s)
Artifacts: https://github.com/AkihiroSuda/fuse-overlayfs/releases/tag/test-cross-202006191303
> CI: Upload static release binaries

- NEWS
- main.c
we were mistakenly using the overflow GID also for UIDs lookups.  Not a big issue as they usually have the same value.
> main: fix lookup for overflow uid

- utils.c
Neither uClibc nor uClibc-ng support O_TMPFILE. Define it in utils.c if
not defined.
Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
> utils.c: fix build on uclibc

- main.c
Closes: https://github.com/containers/fuse-overlayfs/issues/225
> main: fix segfault if no mountpoint specified

- contrib/fix-mode.py
- direct.c
- fuse-overlayfs.h
introduce a new xattr "user.fuseoverlayfs.override_stat" that permit
to override the reported uid/gid/mode for lower layers.
It enables sharing storage among different users.
Since it is not possible to use "user.*" xattrs for symlinks, provide
also a privileged variant "security.fuseoverlayfs.override_stat", so
the root user can create the xattr for symlinks as well.
A script "fix-mode.py" is provided for converting an existing
layer/storage to the new model.  It is a destructive operation as
every file is converted to mode 0755, thus it is not usable anymore
with native overlay, or older versions of fuse-overlayfs.
Example with Podman:
Rootless:
Modify /.config/containers/storage.conf and add under storage.options:
additionalimagestores = ["/var/lib/shared-storage"]
Assuming an empty …
> fuse-overlays: introduce xattr to override gid/uid/mode

- main.c
honor the specified flags to fchownat.
commit 50787d38278fa41c1b3f8167ccfe13ec83d9a063 introduced the
regression.
Closes: https://github.com/containers/fuse-overlayfs/issues/233
> main: honor chownat flags

- main.c
- tests/fedora-installs.sh
adding the .wh. prefix could cause the lookup to cross the f_namemax limit and fail the lookup with ENAMETOOLONG.  If the lookup fails with ENAMETOOLONG then the whiteout file doesn't exist.
Also, prevent files longer than the new limit can be created, otherwise it won't be possible to create whiteout files.
Closes: https://github.com/containers/fuse-overlayfs/issues/236
> main: prevent ENAMETOOLONG for whiteout files

- fuse-overlayfs.1
- main.c
if the reference held by the directory is the last one, it would miss to clean up the inode.  Fix it by calling do_forget.
Closes: https://github.com/containers/fuse-overlayfs/issues/238
> main: fix a potential leak and be more aggressive on releasing inodes

- main.c
make sure the inodes are created with mode 0755 when using
xattr_permissions, otherwise the original permission could prevent
running on NFS.  Requires Linux 5.9 for NFS with xattr support.
> main: create inodes with 0755 with xattr_permissions

- fuse-overlayfs.1
Signed-off-by: Vasily Tarasov <vtarasov@us.ibm.com>
> man: removing the duplicate description of workdir option

- main.c
upstream Linux added an option "volatile" for overlay mounts that has
the same meaning as fsync=0 already supported by fuse-overlayfs.
> main: honor option volatile

- direct.c
- fuse-overlayfs.h
- main.c
if a mapping is specified, make sure it is always honored, also when
using xattr permissions.
Closes: https://github.com/containers/fuse-overlayfs/issues/253
> main: always remap ids when specified

- main.c
- tests/fedora-installs.sh
if a file is delete and not accessible from the file system, but it is
still referenced, we must be able to open and use it.
> main: open hidden files

- main.c
it is reserved for internal usage with containers/storage.
> main: block setting the user.containers. xattr

- fuse-overlayfs.h
- main.c
if we are adding a new file to a directory, the parent directory must
be invalidated if it is in the middle of a opendir/releasedir
otherwise the added files won't be cached.
Closes: https://github.com/containers/fuse-overlayfs/issues/259
> main: invalidate directory cache on create/rename

- main.c
- tests/fedora-installs.sh
when device whiteouts are created (supported for unprivileged users in
newer Linux kernels) make sure the RENAME_NOREPLACE flag is dropped
when renaming the file on top of an existing whiteout.
Closes: https://github.com/containers/fuse-overlayfs/issues/273
> fuse-overlayfs: fix renameat2(RENAME_NOREPLACE)

- main.c
- tests/fedora-installs.sh
if a whiteout was created as part of a rename operation, mark the directory content as not loaded so to avoid some optimizations when a whiteout file must be deleted.
Closes: https://github.com/containers/fuse-overlayfs/issues/279
> main: mark directory not loaded on rename

- fuse-overlayfs.1
- fuse-overlayfs.1.md
- fuse-overlayfs.h
- main.c
This is a continuation of the discussion in #193 and solves #182.
We've been using (something like) this internally for almost a year, and for our limited use case it works fine.
Anything that relies on accurate values for st_nlink will obviously break if this option is enabled.
> main: Add option static_nlink to set st_nlink to 1 for all directories

- main.c
- tests/fedora-installs.sh
fix reading extended attributes longer than 256 bytes.
Closes: https://github.com/containers/fuse-overlayfs/issues/284
> main: fix reading xattrs longer than 256 bytes

- main.c
When handling `setattr()` requests that involve changing the access/modification time, this library sets `tv_sec=UTIME_OMIT` or `tv_sec=UTIME_NOW` before calling `utimensat()` or `futimens()`:
https://github.com/containers/fuse-overlayfs/blob/11ad142525a606f327745210e709dcbd23844fd2/main.c#L3950-L3967
This is wrong. [`utimensat(2)`](https://man7.org/linux/man-pages/man2/utimensat.2.html) specifies that `UTIME_OMIT` or `UTIME_NOW` should be stored in **`tv_nsec`**, not `tv_sec`.
The way this bug manifests is that calling e.g. `utimensat(AT_FDCWD, "/overlay/file", [{.tv_nsec=UTIME_OMIT}, {...}], 0)` on a file in a fuse-overlayfs will cause file's access timestamp to be reset to `2004-01-10 13:37:02.000000000`. This time corresponds to a Unix timestamp of `1073741822`, which is the value of …
> Fix flaws in utimensat() handling

- main.c
move the logic for loading the directory content at readdir time when
the offset is set to 0, so that any new file to the directory is
propagated.
Closes: https://github.com/containers/fuse-overlayfs/issues/287
> main: move directory load at readdir time

- main.c
fix a fd leak on the error exit path.
Closes: https://github.com/containers/fuse-overlayfs/issues/289
> main, rename: fix leak on error

- configure.ac
Closes: https://github.com/containers/fuse-overlayfs/issues/294
> configure.ac: tag -dev version

- .github/workflows/test.yaml
- NEWS
- configure.ac
- main.c
Fix an invalid access when filtering internal xattrs.
The size passed to memmove was longer than the remaining bytes to process.
As part of the fix: move the filtering logic to a separate function.
Closes: https://github.com/containers/fuse-overlayfs/issues/293
> main: fix invalid access when filtering xattrs

- main.c
Closes: https://github.com/containers/fuse-overlayfs/issues/304
> main: enable POSIX ACLs

- main.c
- tests/fedora-installs.sh
If a dir is opaque, there's no need to create a whiteout within it as
the opacity will block out any files from lower dirs already anyways.
The kernel's overlay implementation also doesn't currently handle
whiteouts in opaque dirs very well (the whiteout shows up in readdir
calls but can't be stat'd), so this fix also improves compatibility
between fuse-overlay and the kernel's overlay a bit too.
Signed-off-by: Erik Sipsma <erik@sipsma.dev>
Fixes #306
> Don't create whiteout files in opaque dirs.

- direct.c
- tests/fedora-installs.sh
always use llistxattr and lgetxattr for listing and reading xattrs so
that the open/openat2 call doesn't fail when accessing a device.
Closes: https://github.com/containers/fuse-overlayfs/issues/312
> fuse-overlayfs: fix read xattrs for devices

- main.c
fix the check for FUSE_CAP_POSIX_ACL.  commit
0a659e75ef61456bda1fa4b0b30117296f66f4fe introduced the issue.
It is needed to run fuse-overlayfs on RHEL 7 kernels.
> main: fix check for FUSE_CAP_POSIX_ACL

- NEWS
- configure.ac
- set FUSE_CAP_POSIX_ACL only when it is supported by FUSE.
- treat statx failure with EINVAL as ENOSYS, so that the fallback is attempted.
> NEWS: tag 1.7.1

- NEWS
- configure.ac
- main.c
- tests/fedora-installs.sh
fix lookup if the underlying file is a symlink, while it is a directory on the upper layer.
Closes: https://github.com/containers/fuse-overlayfs/issues/337
> main: fix lookup if underlying file is a symlink

- .github/workflows/release.yaml
- Containerfile.cross
Test release: https://github.com/AkihiroSuda/fuse-overlayfs/releases/tag/test-cross-20220501-1
Build logs: https://github.com/AkihiroSuda/fuse-overlayfs/releases/tag/test-cross-20220501-1
- - -
The base image of Containerfile.cross is changed from debian:10 to ubuntu:22.04 for supporting riscv64.
This PR also contains several refactoring changes such as removing dependency on QEMU user mode emulation.
> release.yaml: add riscv64 build

- main.c
Fixes #349 
Also works around #348 on systems with older sed
Since there is already handling for the `default` case where we use a path instead of a file descriptor, we can just as well fall back to it if opening a file descriptor fails.
Note that I'm not familiar with the codebase and possible side effects that this might have.
> Fix setting attributes on file without permissions

- main.c
Set correct value of `RENAME_NOREPLACE` when `RENAME_EXCHANGE` is not
already defined i.e use `1 << 0` instead of `1 << 2` which seems
incorrect.
Reference: https://github.com/torvalds/linux/blob/f2906aa863381afb0015a9eb7fefad885d4e5a56/include/uapi/linux/fs.h#L50-L52
Closes: https://github.com/containers/fuse-overlayfs/issues/353
> main: set correct value of `RENAME_NOREPLACE` ifndef `RENAME_EXACHANGE`

- direct.c
instead of using the lgetxattr and llistxattr system calls on the
entire file path, use the /proc/self/fd/$FD/$RELATIVE_PATH path
instead so that the lookup is relative to the lower dir file
descriptor that is already open.
Closes: https://github.com/containers/fuse-overlayfs/issues/364
> direct: use /proc/self/fd to read xattrs

- main.c
when creating a new file/directory, inherit the ACL from the parent directory.
Closes: https://github.com/containers/fuse-overlayfs/issues/363
> main: inherit ACLs for new files/dirs

- main.c
if the file was deleted, access it through the hidden_dirfd.
Closes: https://github.com/containers/fuse-overlayfs/issues/368
> main: fix copy_file_range for deleted files

- .github/workflows/test.yaml
Upload fuse-overlayfs as job artifacts on CI.
Context: I [was asked](https://github.com/NVIDIA/enroot/issues/132#issuecomment-1219025116) to try the latest commit of fuse-overlayfs to see whether it fixes an issue in enroot.
When trying to install buildah on ubuntu 20.04 a couple of days ago, I got a conflict for `runc` (runc vs moby-runc).
After removing the conflicting dependency, I ran the container but still ran into errors, both for `Containerfile.static.ubuntu` and `Containerfile.static.fedora` (maybe related to access to package repositories from the Azure VM, I didn't write down the issue), and I stopped.
If I understand correctly, then `fuse-overlayfs` is anyhow a standalone binary that needs to be built only once for a given architecture (?), and this already happens in your CI …
> upload builds from CI

- main.c
fix the check for writeable /proc to use statfs instead of statvfs, and use the unitialized statvfs structure to check for the writeable bit.
Closes: https://github.com/containers/fuse-overlayfs/issues/397
> main: fix check for writeable /proc

- NEWS
- fuse-overlayfs.h
- main.c
cache the number of links for a directory instead of calculating it on every stat.  It makes a huge difference when the directory has a lot of entries.
Closes: https://github.com/containers/fuse-overlayfs/issues/401
> main: fix performance issue with large dirs

- .github/workflows/release.yaml
- Containerfile.cross
The binaries are now bit-for-bit reproducible (<https://reproducible-builds.org/>):
```bash
docker buildx build \
-o /tmp/fuse-overlayfs-builds \
--build-arg SOURCE_DATE_EPOCH=$(git log -1 --pretty=%ct) \
--platform=amd64,arm64,arm,s390x,ppc64le,riscv64 \
-f Containerfile.cross .
```
This ensures that the binaries are not built from any unpublished source.
- Implementation is similar to <https://github.com/rootless-containers/slirp4netns/compare/v1.2.1...06b1097203487955714dcc1d7638c769d3a5eb89>
- `/etc/apt/sources.list` is modified to use <http://snapshot.ubuntu.com> using <https://github.com/reproducible-containers/repro-sources-list.sh>.
- As <http://snapshot.ubuntu.com> is slow, `/var/cache/apt` is cached on GHA using <https://github.com/reproducible-containers/buildkit-cache-dance>. …
> CI: release: enable reproducible builds

- .github/workflows/release.yaml
`hub` was deprecated and removed from GitHub Actions runners:
- https://github.com/actions/runner-images/issues/8362
> release.yaml: migrate from `hub` to `gh`

- main.c
when a directory is copied up, propagate its mode if using xattrs permissions.
Closes: https://github.com/containers/fuse-overlayfs/issues/407
> main: propagate xattrs permissions with copyup

- .clang-format
New clang versions throw error like below, following commit fixes that
```console
.clang-format:26:1: error: duplicated mapping key 'AllowShortIfStatementsOnASingleLine'
AllowShortIfStatementsOnASingleLine: false
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```
Version which i tried: `clang-format version 17.0.6`
Following change should not produce any diff in `.c` or `.h` files.
> .clang-format: remove duplicated mapping key which breaks newer `clang` formatters.

- .github/workflows/release.yaml
- .github/workflows/test.yaml
- main.c
- tests/fedora-installs.sh
- utils.c
- utils.h
Needs: https://github.com/containers/storage/pull/2183
> main: use extended override xattr

- configure.ac
The version string should update as "1.14" when we have stable release:
-AC_INIT([fuse-overlayfs], [1.13-dev], [giuseppe@scrivano.org])
+AC_INIT([fuse-overlayfs], [1.14], [giuseppe@scrivano.org])
But since we had already get
https://github.com/containers/fuse-overlayfs/releases/tag/v1.14 since 2024-06-28, here we bump the version string to "1.15-dev" for next stable release.
Fixes https://github.com/containers/fuse-overlayfs/issues/438
> Update AC_INIT to 1.15-dev

- .github/workflows/test.yaml
- main.c
- tests/fedora-installs.sh
Allow directory paths specified for lowerdir, upperdir, workdir, and the mountpoint to contain colon characters.
Previously, colons were unconditionally treated as separators, making it impossible to use directories with colons in their names.
Closes: https://github.com/containers/fuse-overlayfs/issues/440
> main: Allow escaped colons in directory paths

- lib/hash.c
- lib/hash.h
- m4/00gnulib.m4
- m4/gnulib-common.m4
- m4/zzgnulib.m4
- main.c
the function is deprecated in gnulib
Closes: https://github.com/containers/fuse-overlayfs/issues/442
> main: use hash_remove instead of hash_delete
