main.c

Consider the mountpoint to be the last argument passed, so that
fuse-overlayfs can be used as a mount helper.
This enables to run the github.com/amir73il/unionmount-testsuite
testsuite on fuse-overlayfs.

fuse-overlayfs: mountpoint is the last argument passed

---

main.c

if we are trying to move over an existing whiteout, try a rename2(...,
RENAME_EXCHANGE) first, so in one atomic operation we get both the
file renamed and the whiteout created in the old source.

fuse-overlayfs: try RENAME_EXCHANGE if the destination is a whiteout

---

configure.ac

- fail if libfuse is not found.
- drop a bunch of files that are not used.

build: a couple of cleanups

---

COPYING

COPYING: add file

---

Dockerfile.static
README.md

Fixes: #9 
Signed-off-by: Vincent Batts <vbatts@hashbangbash.com>

*: some build hints and static link example

---

main.c

main: improve errors logging

---

Makefile.am
fuse-overlayfs.1
fuse-overlayfs.1.md

Closes: https://github.com/containers/fuse-overlayfs/issues/7

man: add man page

---

main.c

avoid blocking on opening a fifo:
Closes: https://github.com/containers/fuse-overlayfs/issues/21

fuse-overlayfs: use O_NONBLOCK for opening files

---

configure.ac
main.c

fuse-overlayfs: tag version 0.2

---

main.c

Increase the soft limit for the open files to the hard limit.
Closes: https://github.com/containers/fuse-overlayfs/issues/34

fuse-overlays: bump max open files to hard limit

---

main.c

Closes: https://github.com/containers/libpod/issues/2091

fuse-overlayfs: create symlinks with the correct owner

---

main.c

mknod: honor umask from the calling process

---

main.c

mkdir: honor calling process umask

---

Makefile.am
configure.ac

fuse-overlayfs: tag release 0.3

---

main.c

When a file is created with restricted permissions (like 000), ftruncate() should
still work as long as the fd is open. Use fi->fh to fix that and avoid the call to
openat() which failed in that case.

setattr: use fd from fi->fh for ftruncate()

---

configure.ac
main.c

a few patches to address portability to musl libc
Closes: https://github.com/containers/fuse-overlayfs/issues/50

Fix musl build

---

fuse-overlayfs.1
fuse-overlayfs.1.md
main.c

Closes: https://github.com/containers/fuse-overlayfs/issues/57

fuse-overlayfs: print config settings only with --debug

---

main.c

Use reflinks if they are supported by the underlying file system.
On my system, using XFS and reflinks, chowning recursively a directory
passed from:
User time (seconds): 0.02
System time (seconds): 0.34
Percent of CPU this job got: 8%
Elapsed (wall clock) time (h:mm:ss or m:ss): 0:04.52
to:
User time (seconds): 0.02
System time (seconds): 0.22
Percent of CPU this job got: 17%
Elapsed (wall clock) time (h:mm:ss or m:ss): 0:01.45
the performance improvement can be higher if the directory is made of
few but bigger files.

main: copyup uses reflinks if possible

---

main.c

Closes: https://github.com/containers/fuse-overlayfs/issues/59

fuse-overlayfs: support some ioctls

---

main.c

Closes: https://github.com/containers/libpod/issues/3021

fuse-overlayfs: add support for .wh..wh..opq variant

---

.travis.yml

travis: enable containers/storage tests

---

main.c

these are just some cleanup patches that I've prepared while working on a different feature:
https://github.com/containers/fuse-overlayfs/compare/master...giuseppe:multiple-sources?expand=1

fuse-overlayfs: some cleanups

---

main.c

allow to override the default timeout value we specify for an entry
validity.

fuse-overlayfs: add new option "timeout"

---

configure.ac

configure.ac: tag new release

---

.travis.yml
configure.ac
main.c
tests/fedora-installs.sh

regression introduced with 7dcef0769b1521b8f14bdee58339c26140466c85
Reported here: https://bodhi.fedoraproject.org/updates/FEDORA-2019-fff1ded16e#comment-958825
As part of the PR, tag also another release

rm: fix rm'ing a file

---

configure.ac
main.c
tests/fedora-installs.sh

This reverts commit b4ef7a8fff0a76ac05dccb59edbbb49971b76420.
Closes: https://github.com/containers/fuse-overlayfs/issues/86

Revert "main: add helper function to get fd to the upper layer"

---

configure.ac
main.c

build: fix build with older versions of libfuse

---

main.c

avoid some unnecessary syscalls when creating new files.  It improves file creation times by ~20%

perf: improve performance for mkdir and open(O_CREAT)

---

.lgtm.yml

add instructions for building on lgtm.com.

.lgtm.yml: new file

---

configure.ac

configure.ac: tag new version 0.5

---

main.c

node already keeps st_mode in cache so there is no need of the
additional stat to find out the file type.

main: use cached st_mode

---

.travis.yml

travis: fix build issue with meson master

---

NEWS
configure.ac

configure.ac: tag 0.6.2

---

README.md

Just a few improvements to the `README.md` in order to facilitate newcomers.

More detailed build instructions, closes #107

---

Makefile.am
main.c
tests/fedora-installs.sh
tests/suid-test.c

restore the inode mode if there is a writepage request that could
reset the setuid bit.
Closes: https://github.com/containers/fuse-overlayfs/issues/127

writeback: restore suid mode after write

---

main.c
tests/fedora-installs.sh

Closes: https://github.com/containers/fuse-overlayfs/issues/138

main: honor opaque whiteout

---

fuse_overlayfs_error.h
main.c
plugin-manager.c

Closes: https://github.com/containers/fuse-overlayfs/issues/145

build: fix build on musl

---

.travis.yml
Dockerfile.alpine

.travis: test build on Alpine

---

fuse-overlayfs.h
main.c

main: drop special handling for security.capability

---

main.c
utils.c

fuse-overlayfs: fix some warnings reported by clang

---

main.c
utils.c

Just some nits I came across during looking at the code.

Fix dead increment and assignments

---

NEWS
configure.ac

configure.ac: tag 0.7.3

---

NEWS
configure.ac

release: tag 0.7.4

---

NEWS
configure.ac
main.c
utils.c

listxattr/getxattr: do not access private xattrs

---

.travis.yml
main.c
utils.c

if there is no origin xattr specified, do not overwrite the ino
number.
Closes: https://github.com/containers/fuse-overlayfs/issues/177

main: lookup skip ino if there is no origin

---

NEWS
configure.ac

configure.ac: tag 0.7.6

---

fuse-overlayfs.h
main.c
tests/fedora-installs.sh

calculate the nlink for the directory on each stat.

main: drop nlink optimization

---

NEWS
configure.ac

configure.ac, NEWS: tag 0.7.8

---

NEWS
configure.ac

fuse-overlays: release 1.0.0

---

main.c

main.c: accept "ro" as a mount option

---

.travis.yml
direct.c
main.c
utils.c
utils.h

main: use openat2 where available

---

main.c
tests/fedora-installs.sh

Closes: https://github.com/containers/fuse-overlayfs/issues/204

main: fix set mtime for a symlink

---

.travis.yml
main.c
tests/unlink.sh

fuse-overlayfs: fix different issues reported by static analysis

---

NEWS

NEWS: fix typo

---

direct.c

Signed-off-by: Asaf Kahlon <asafka7@gmail.com>

direct.c: fix compilation with musl

---

NEWS
main.c

NEWS: tag 1.1.2

---

direct.c
fuse-overlayfs.h
main.c
utils.c
utils.h

it is still experimental but so far I could use yum in a container.

main: support writing uid/gid/mode to xattr

---

.travis.yml

travis: update to focal

---

fuse-overlayfs.1.md
fuse-overlayfs.h
lib/hash.c
main.c

Signed-off-by: Daniel J Walsh <dwalsh@redhat.com>

Fix problems found by codespell

---

NEWS

NEWS: tag 1.2

---

Containerfile.cross
Makefile.am
configure.ac

build: check for go-md2man

---

fuse-overlayfs.h
main.c

See issue https://github.com/containers/fuse-overlayfs/issues/241

Add squash_to_root mount option

---

configure.ac

configure.ac: set version to 1.2.0+dev

---

main.c

fix typo in debug log

---

utils.c

utils: enable override only for directories and files

---

NEWS
configure.ac

NEWS: tag 1.3

---

fuse-overlayfs.1
fuse-overlayfs.1.md
fuse-overlayfs.h
main.c

add a more generic variant of squash_to_root.

main: add squash_to_uid and squash_to_gid

---

NEWS
configure.ac
main.c

NEWS: tag 1.4.0

---

main.c

on newer kernels unprivileged users can create whiteout devices.  If
the whiteout device creation failed with EEXIST, check whether the
existing file is already a whiteout.
Closes: https://github.com/containers/fuse-overlayfs/issues/271

main: check if whiteout device already exists

---

.github/workflows/test.yaml
main.c
tests/fedora-installs.sh
utils.h

src: fix some defects found by static analysis

---

NEWS
configure.ac

NEWS: tag 1.5

---

main.c

main: fix some issues reported by static analysis

---

main.c

main: drop unused variables

---

.github/workflows/test.yaml
fuse-overlayfs.h
main.c
tests/unpriv.sh

Fixes #307 (which contains full details about the encountered issue).

Fix operations on read-only files when running unprivileged.

---

NEWS
configure.ac
tests/fedora-installs.sh

NEWS: tag 1.7

---

fuse-overlayfs.1
fuse-overlayfs.1.md
fuse-overlayfs.h
main.c

main: add a mount flag to disable ACLs

---

main.c

native overlay uses user.overlay to store the overlay metadata instead
of trusted.overlay, let's honor it as well.
Closes: https://github.com/containers/fuse-overlayfs/issues/328

main: honor user.overlay. xattrs

---

NEWS
configure.ac

NEWS: tag 1.8

---

NEWS
configure.ac
main.c

fix two issues:
- https://github.com/containers/fuse-overlayfs/issues/330
- https://github.com/containers/fuse-overlayfs/issues/333

NEWS: tag 1.8.1

---

.github/workflows/test.yaml

.github: fix git clone

---

main.c

- Create source whiteout only when needed (fixes #327)
- Fix missing source whiteout when destination is whiteout (fixes #354)
- Try the EXCHANGE trick also when NOREPLACE is set
- Clean up the renaming code
Notes:
- I copied the `src_needs_whiteout` check from the `hide_node` function. In that function, the check is much longer but I can't come up with any reason why it has those extra parts.
- I don't know what the `pnode->loaded = 0` line does. It was there before and I didn't remove it.

Refactor and fix rename code

---

configure.ac
utils.h

1. fixes build error with musl (limits.h)
2. clarifies FUSE version in configure error
3. cleans up utils.h

musl fix and various tweaks

---

main.c

since fuse-overlayfs needs a writeable /proc mount, add some checks to validate it.
Closes: https://github.com/containers/fuse-overlayfs/issues/137

main: add checks for valid /proc mount

---

fuse-overlayfs.h
main.c

Closes: https://github.com/containers/fuse-overlayfs/issues/339

main: print a warning if an argument is ignored

---

NEWS
configure.ac
main.c

Closes: https://github.com/containers/fuse-overlayfs/issues/380

NEWS: tag 1.10

---

COPYING
direct.c
fuse-overlayfs.h
fuse_overlayfs_error.h
lib/hash.c
lib/hash.h
main.c
plugin-manager.c
plugin-manager.h
plugin.h
rpm/fuse-overlayfs.spec.template
utils.c
utils.h

the contributors agreed on the change in the attached issue.
Closes: https://github.com/containers/fuse-overlayfs/issues/387

fuse-overlays: change license to GPLv2+

---

.clang-format
Makefile.am
direct.c
fuse-overlayfs.h
fuse_overlayfs_error.h
main.c
plugin-manager.c
plugin-manager.h
plugin.h
tests/suid-test.c
utils.c
utils.h

add a clang-format definition file and apply it to the code.

code: add clang-format

---

main.c

this was already the assumption in the source code.

main: automatically cleanup newpath

---

main.c

Remove unsupported option "lazytime"
